// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// VM
Rcpp::NumericMatrix VM(const Rcpp::IntegerMatrix& viewshed, const Rcpp::NumericMatrix& dsm, const Rcpp::NumericVector viewpt, const double h, const double resolution);
RcppExport SEXP _viewscape_VM(SEXP viewshedSEXP, SEXP dsmSEXP, SEXP viewptSEXP, SEXP hSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type viewshed(viewshedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type viewpt(viewptSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(VM(viewshed, dsm, viewpt, h, resolution));
    return rcpp_result_gen;
END_RCPP
}
// dsm_to_pano
NumericMatrix dsm_to_pano(NumericMatrix dsm, double vpt_x, double vpt_y, double vpt_z, int pano_height, int pano_width, double xres, double yres, double ares, double step_size, double max_dist, double sky_value, double sky_threshold, double orientation);
RcppExport SEXP _viewscape_dsm_to_pano(SEXP dsmSEXP, SEXP vpt_xSEXP, SEXP vpt_ySEXP, SEXP vpt_zSEXP, SEXP pano_heightSEXP, SEXP pano_widthSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP aresSEXP, SEXP step_sizeSEXP, SEXP max_distSEXP, SEXP sky_valueSEXP, SEXP sky_thresholdSEXP, SEXP orientationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_x(vpt_xSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_y(vpt_ySEXP);
    Rcpp::traits::input_parameter< double >::type vpt_z(vpt_zSEXP);
    Rcpp::traits::input_parameter< int >::type pano_height(pano_heightSEXP);
    Rcpp::traits::input_parameter< int >::type pano_width(pano_widthSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< double >::type ares(aresSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< double >::type sky_value(sky_valueSEXP);
    Rcpp::traits::input_parameter< double >::type sky_threshold(sky_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type orientation(orientationSEXP);
    rcpp_result_gen = Rcpp::wrap(dsm_to_pano(dsm, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, ares, step_size, max_dist, sky_value, sky_threshold, orientation));
    return rcpp_result_gen;
END_RCPP
}
// dsm_to_equirectangular
NumericMatrix dsm_to_equirectangular(NumericMatrix dsm, double vpt_x, double vpt_y, double vpt_z, int pano_height, int pano_width, double xres, double yres, double step_size, double max_dist, double sky_value, double sky_threshold, double orientation);
RcppExport SEXP _viewscape_dsm_to_equirectangular(SEXP dsmSEXP, SEXP vpt_xSEXP, SEXP vpt_ySEXP, SEXP vpt_zSEXP, SEXP pano_heightSEXP, SEXP pano_widthSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP step_sizeSEXP, SEXP max_distSEXP, SEXP sky_valueSEXP, SEXP sky_thresholdSEXP, SEXP orientationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_x(vpt_xSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_y(vpt_ySEXP);
    Rcpp::traits::input_parameter< double >::type vpt_z(vpt_zSEXP);
    Rcpp::traits::input_parameter< int >::type pano_height(pano_heightSEXP);
    Rcpp::traits::input_parameter< int >::type pano_width(pano_widthSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< double >::type sky_value(sky_valueSEXP);
    Rcpp::traits::input_parameter< double >::type sky_threshold(sky_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type orientation(orientationSEXP);
    rcpp_result_gen = Rcpp::wrap(dsm_to_equirectangular(dsm, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, step_size, max_dist, sky_value, sky_threshold, orientation));
    return rcpp_result_gen;
END_RCPP
}
// dsm_semantic_to_pano
List dsm_semantic_to_pano(NumericMatrix dsm, NumericMatrix semantic, double vpt_x, double vpt_y, double vpt_z, int pano_height, int pano_width, double xres, double yres, double ares, double step_size, double max_dist, double sky_value, double sky_threshold, double orientation);
RcppExport SEXP _viewscape_dsm_semantic_to_pano(SEXP dsmSEXP, SEXP semanticSEXP, SEXP vpt_xSEXP, SEXP vpt_ySEXP, SEXP vpt_zSEXP, SEXP pano_heightSEXP, SEXP pano_widthSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP aresSEXP, SEXP step_sizeSEXP, SEXP max_distSEXP, SEXP sky_valueSEXP, SEXP sky_thresholdSEXP, SEXP orientationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type semantic(semanticSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_x(vpt_xSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_y(vpt_ySEXP);
    Rcpp::traits::input_parameter< double >::type vpt_z(vpt_zSEXP);
    Rcpp::traits::input_parameter< int >::type pano_height(pano_heightSEXP);
    Rcpp::traits::input_parameter< int >::type pano_width(pano_widthSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< double >::type ares(aresSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< double >::type sky_value(sky_valueSEXP);
    Rcpp::traits::input_parameter< double >::type sky_threshold(sky_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type orientation(orientationSEXP);
    rcpp_result_gen = Rcpp::wrap(dsm_semantic_to_pano(dsm, semantic, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, ares, step_size, max_dist, sky_value, sky_threshold, orientation));
    return rcpp_result_gen;
END_RCPP
}
// dsm_to_color_equirectangular
List dsm_to_color_equirectangular(NumericMatrix dsm, NumericMatrix sat_r, NumericMatrix sat_g, NumericMatrix sat_b, double vpt_x, double vpt_y, double vpt_z, int pano_height, int pano_width, double xres, double yres, double step_size, double max_dist, double sky_threshold, double orientation, double sky_r, double sky_g, double sky_b);
RcppExport SEXP _viewscape_dsm_to_color_equirectangular(SEXP dsmSEXP, SEXP sat_rSEXP, SEXP sat_gSEXP, SEXP sat_bSEXP, SEXP vpt_xSEXP, SEXP vpt_ySEXP, SEXP vpt_zSEXP, SEXP pano_heightSEXP, SEXP pano_widthSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP step_sizeSEXP, SEXP max_distSEXP, SEXP sky_thresholdSEXP, SEXP orientationSEXP, SEXP sky_rSEXP, SEXP sky_gSEXP, SEXP sky_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sat_r(sat_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sat_g(sat_gSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sat_b(sat_bSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_x(vpt_xSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_y(vpt_ySEXP);
    Rcpp::traits::input_parameter< double >::type vpt_z(vpt_zSEXP);
    Rcpp::traits::input_parameter< int >::type pano_height(pano_heightSEXP);
    Rcpp::traits::input_parameter< int >::type pano_width(pano_widthSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< double >::type sky_threshold(sky_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type orientation(orientationSEXP);
    Rcpp::traits::input_parameter< double >::type sky_r(sky_rSEXP);
    Rcpp::traits::input_parameter< double >::type sky_g(sky_gSEXP);
    Rcpp::traits::input_parameter< double >::type sky_b(sky_bSEXP);
    rcpp_result_gen = Rcpp::wrap(dsm_to_color_equirectangular(dsm, sat_r, sat_g, sat_b, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, step_size, max_dist, sky_threshold, orientation, sky_r, sky_g, sky_b));
    return rcpp_result_gen;
END_RCPP
}
// dsm_semantic_to_equirectangular
List dsm_semantic_to_equirectangular(NumericMatrix dsm, NumericMatrix semantic, double vpt_x, double vpt_y, double vpt_z, double ground_z, int pano_height, int pano_width, double xres, double yres, double step_size, double max_dist, double sky_value, double sky_threshold, double orientation, bool extrude_semantic);
RcppExport SEXP _viewscape_dsm_semantic_to_equirectangular(SEXP dsmSEXP, SEXP semanticSEXP, SEXP vpt_xSEXP, SEXP vpt_ySEXP, SEXP vpt_zSEXP, SEXP ground_zSEXP, SEXP pano_heightSEXP, SEXP pano_widthSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP step_sizeSEXP, SEXP max_distSEXP, SEXP sky_valueSEXP, SEXP sky_thresholdSEXP, SEXP orientationSEXP, SEXP extrude_semanticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type semantic(semanticSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_x(vpt_xSEXP);
    Rcpp::traits::input_parameter< double >::type vpt_y(vpt_ySEXP);
    Rcpp::traits::input_parameter< double >::type vpt_z(vpt_zSEXP);
    Rcpp::traits::input_parameter< double >::type ground_z(ground_zSEXP);
    Rcpp::traits::input_parameter< int >::type pano_height(pano_heightSEXP);
    Rcpp::traits::input_parameter< int >::type pano_width(pano_widthSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< double >::type sky_value(sky_valueSEXP);
    Rcpp::traits::input_parameter< double >::type sky_threshold(sky_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type orientation(orientationSEXP);
    Rcpp::traits::input_parameter< bool >::type extrude_semantic(extrude_semanticSEXP);
    rcpp_result_gen = Rcpp::wrap(dsm_semantic_to_equirectangular(dsm, semantic, vpt_x, vpt_y, vpt_z, ground_z, pano_height, pano_width, xres, yres, step_size, max_dist, sky_value, sky_threshold, orientation, extrude_semantic));
    return rcpp_result_gen;
END_RCPP
}
// get_depths
NumericVector get_depths(double px, double py, NumericVector& x, NumericVector& y, int num);
RcppExport SEXP _viewscape_get_depths(SEXP pxSEXP, SEXP pySEXP, SEXP xSEXP, SEXP ySEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type px(pxSEXP);
    Rcpp::traits::input_parameter< double >::type py(pySEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type num(numSEXP);
    rcpp_result_gen = Rcpp::wrap(get_depths(px, py, x, y, num));
    return rcpp_result_gen;
END_RCPP
}
// sectorMask
Rcpp::IntegerMatrix sectorMask(const Rcpp::IntegerMatrix& viewshed, const Rcpp::NumericVector viewpt, const Rcpp::NumericVector fov);
RcppExport SEXP _viewscape_sectorMask(SEXP viewshedSEXP, SEXP viewptSEXP, SEXP fovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type viewshed(viewshedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type viewpt(viewptSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type fov(fovSEXP);
    rcpp_result_gen = Rcpp::wrap(sectorMask(viewshed, viewpt, fov));
    return rcpp_result_gen;
END_RCPP
}
// view_tree
Rcpp::IntegerMatrix view_tree(const Rcpp::NumericVector& viewpoint, const Rcpp::NumericMatrix& dsm, const double h, const int max_dis, const double refraction_factor);
RcppExport SEXP _viewscape_view_tree(SEXP viewpointSEXP, SEXP dsmSEXP, SEXP hSEXP, SEXP max_disSEXP, SEXP refraction_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type viewpoint(viewpointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type max_dis(max_disSEXP);
    Rcpp::traits::input_parameter< const double >::type refraction_factor(refraction_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(view_tree(viewpoint, dsm, h, max_dis, refraction_factor));
    return rcpp_result_gen;
END_RCPP
}
// reference
Rcpp::IntegerMatrix reference(const Rcpp::NumericVector& viewpoint, const Rcpp::NumericMatrix& dsm, const double h, const int max_dis, const double refraction_factor);
RcppExport SEXP _viewscape_reference(SEXP viewpointSEXP, SEXP dsmSEXP, SEXP hSEXP, SEXP max_disSEXP, SEXP refraction_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type viewpoint(viewpointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type max_dis(max_disSEXP);
    Rcpp::traits::input_parameter< const double >::type refraction_factor(refraction_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(reference(viewpoint, dsm, h, max_dis, refraction_factor));
    return rcpp_result_gen;
END_RCPP
}
// LOS
Rcpp::IntegerMatrix LOS(const Rcpp::NumericVector& viewpoint, const Rcpp::NumericMatrix& dsm, const double h, const int max_dis, const double refraction_factor);
RcppExport SEXP _viewscape_LOS(SEXP viewpointSEXP, SEXP dsmSEXP, SEXP hSEXP, SEXP max_disSEXP, SEXP refraction_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type viewpoint(viewpointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type max_dis(max_disSEXP);
    Rcpp::traits::input_parameter< const double >::type refraction_factor(refraction_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(LOS(viewpoint, dsm, h, max_dis, refraction_factor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_viewscape_VM", (DL_FUNC) &_viewscape_VM, 5},
    {"_viewscape_dsm_to_pano", (DL_FUNC) &_viewscape_dsm_to_pano, 14},
    {"_viewscape_dsm_to_equirectangular", (DL_FUNC) &_viewscape_dsm_to_equirectangular, 13},
    {"_viewscape_dsm_semantic_to_pano", (DL_FUNC) &_viewscape_dsm_semantic_to_pano, 15},
    {"_viewscape_dsm_to_color_equirectangular", (DL_FUNC) &_viewscape_dsm_to_color_equirectangular, 18},
    {"_viewscape_dsm_semantic_to_equirectangular", (DL_FUNC) &_viewscape_dsm_semantic_to_equirectangular, 16},
    {"_viewscape_get_depths", (DL_FUNC) &_viewscape_get_depths, 5},
    {"_viewscape_sectorMask", (DL_FUNC) &_viewscape_sectorMask, 3},
    {"_viewscape_view_tree", (DL_FUNC) &_viewscape_view_tree, 5},
    {"_viewscape_reference", (DL_FUNC) &_viewscape_reference, 5},
    {"_viewscape_LOS", (DL_FUNC) &_viewscape_LOS, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_viewscape(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
