# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VM <- function(viewshed, dsm, viewpt, h, resolution) {
    .Call('_viewscape_VM', PACKAGE = 'viewscape', viewshed, dsm, viewpt, h, resolution)
}

dsm_to_pano <- function(dsm, vpt_x, vpt_y, vpt_z, pano_height = 256L, pano_width = 512L, xres = 1.0, yres = 1.0, ares = 0.0174533, step_size = 0.5, max_dist = 500.0, sky_value = -1.0, sky_threshold = 3.0, orientation = 0.0) {
    .Call('_viewscape_dsm_to_pano', PACKAGE = 'viewscape', dsm, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, ares, step_size, max_dist, sky_value, sky_threshold, orientation)
}

dsm_to_equirectangular <- function(dsm, vpt_x, vpt_y, vpt_z, pano_height = 256L, pano_width = 512L, xres = 1.0, yres = 1.0, step_size = 0.5, max_dist = 500.0, sky_value = -1.0, sky_threshold = 3.0, orientation = 0.0) {
    .Call('_viewscape_dsm_to_equirectangular', PACKAGE = 'viewscape', dsm, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, step_size, max_dist, sky_value, sky_threshold, orientation)
}

dsm_semantic_to_pano <- function(dsm, semantic, vpt_x, vpt_y, vpt_z, pano_height = 256L, pano_width = 512L, xres = 1.0, yres = 1.0, ares = 0.0174533, step_size = 0.5, max_dist = 500.0, sky_value = -1.0, sky_threshold = 3.0, orientation = 0.0) {
    .Call('_viewscape_dsm_semantic_to_pano', PACKAGE = 'viewscape', dsm, semantic, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, ares, step_size, max_dist, sky_value, sky_threshold, orientation)
}

dsm_to_color_equirectangular <- function(dsm, sat_r, sat_g, sat_b, vpt_x, vpt_y, vpt_z, pano_height = 256L, pano_width = 512L, xres = 1.0, yres = 1.0, step_size = 0.5, max_dist = 500.0, sky_threshold = 3.0, orientation = 0.0, sky_r = 135.0, sky_g = 206.0, sky_b = 235.0) {
    .Call('_viewscape_dsm_to_color_equirectangular', PACKAGE = 'viewscape', dsm, sat_r, sat_g, sat_b, vpt_x, vpt_y, vpt_z, pano_height, pano_width, xres, yres, step_size, max_dist, sky_threshold, orientation, sky_r, sky_g, sky_b)
}

dsm_semantic_to_equirectangular <- function(dsm, semantic, vpt_x, vpt_y, vpt_z, ground_z, pano_height = 256L, pano_width = 512L, xres = 1.0, yres = 1.0, step_size = 0.5, max_dist = 500.0, sky_value = -1.0, sky_threshold = 3.0, orientation = 0.0, extrude_semantic = FALSE) {
    .Call('_viewscape_dsm_semantic_to_equirectangular', PACKAGE = 'viewscape', dsm, semantic, vpt_x, vpt_y, vpt_z, ground_z, pano_height, pano_width, xres, yres, step_size, max_dist, sky_value, sky_threshold, orientation, extrude_semantic)
}

get_depths <- function(px, py, x, y, num) {
    .Call('_viewscape_get_depths', PACKAGE = 'viewscape', px, py, x, y, num)
}

sectorMask <- function(viewshed, viewpt, fov) {
    .Call('_viewscape_sectorMask', PACKAGE = 'viewscape', viewshed, viewpt, fov)
}

view_tree <- function(viewpoint, dsm, h, max_dis, refraction_factor) {
    .Call('_viewscape_view_tree', PACKAGE = 'viewscape', viewpoint, dsm, h, max_dis, refraction_factor)
}

reference <- function(viewpoint, dsm, h, max_dis, refraction_factor) {
    .Call('_viewscape_reference', PACKAGE = 'viewscape', viewpoint, dsm, h, max_dis, refraction_factor)
}

LOS <- function(viewpoint, dsm, h, max_dis, refraction_factor) {
    .Call('_viewscape_LOS', PACKAGE = 'viewscape', viewpoint, dsm, h, max_dis, refraction_factor)
}

