#' fov_mask
#' @description The fov_mask function is designed to subset a viewshed based on
#' its viewpoint and the field of view
#'
#' @param viewshed viewshed object, generated by compute_viewshed()
#' @param fov Vector, specifying the field of view with two angles in degrees (e.g. c(-45, 45))
#' for masking a viewshed based on its viewpoint.
#' See details.
#'
#' @details Angles are measured clockwise from north, ranging from -180 (exclusive)
#' to 180 (inclusive). The two angles may be given in either order.
#' When \code{fov[1] < fov[2]} the sector spans clockwise from \code{fov[1]} to
#' \code{fov[2]}. When \code{fov[1] > fov[2]} the sector wraps around ±180 (south) —
#' for example \code{c(135, -135)} captures a 90° south-facing arc.
#' \tabular{rrr}{
#' -45 \tab 0 \tab 45 \cr
#' -90 \tab v \tab 90 \cr
#' -135 \tab 180 \tab 135 \cr
#' }
#' Here, 'v' represents the viewpoint. North is 0°, east is 90°, west is -90°,
#' south is ±180°.
#'
#'
#' @return viewshed object
#' @examples
#' # Load a viewpoint
#' test_viewpoint <- sf::read_sf(system.file("test_viewpoint.shp", package = "viewscape"))
#' # load dsm raster
#' dsm <- terra::rast(system.file("test_dsm.tif", package ="viewscape"))
#' # Compute viewshed
#' viewshed <- viewscape::compute_viewshed(dsm,
#'                                         viewpoints = test_viewpoint,
#'                                         offset_viewpoint = 6)
#' # subset viewshed using the field of view (north-facing 120° arc)
#' out <- viewscape::fov_mask(viewshed, c(-60, 60))
#'
#' @seealso [compute_viewshed()]
#' @export
#'

fov_mask <- function(viewshed, fov) {
  if (missing(viewshed))  stop("viewshed is missing")
  if (missing(fov))       stop("fov is missing")
  if (length(fov) != 2)  stop("fov must be a vector of exactly two angles")
  if (fov[1] == fov[2])  stop("fov[1] and fov[2] must not be equal")
  if (any(fov <= -180) || any(fov > 180)) stop("fov angles must be in range (-180, 180]")
  viewshed@visible <- sectorMask(viewshed@visible,
                                 viewshed@viewpos,
                                 fov)
  return(viewshed)
}
